services:
  kasflow:
    build: .
    container_name: kasflow-bot
    restart: unless-stopped
    volumes:
      # Mount data directory for SQLite databases
      - ./src/kasflow/data:/app/src/kasflow/data
    env_file:
      - .env 