services:
  kasflow:
    build: .
    container_name: kasflow-bot
    restart: unless-stopped
    volumes:
      - ./src/kasflow:/app/src/kasflow
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
    env_file:
      - .env 