services:
  kasflow:
    build:
      context: .
    container_name: kasflow-bot
    volumes:
      - ./src/kasflow:/app/src/kasflow
      - ./data:/app/data
    ports:
      - 8443:8443
    env_file:
      - .env