# fly.toml app configuration file generated for kasflow on 2025-08-01T17:51:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kasflow'
primary_region = 'sin'

[build.args]
  DB_ENGINE="postgres"

[deploy]
  release_command = "/app/.venv/bin/alembic upgrade head"

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  LOG_LEVEL="WARNING"
  BOT_NAME="KasflowBot"	
  BOT_MODE="webhook"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

