from pydantic import BaseModel, Field


class ChatState(BaseModel):
    """
    State of the assistant graph.
    """

    message: str = Field(description="Input message from the user")
    chat_response: str = Field(
        description="Response generated by the assistant", default=""
    )
