# Intention schema
from typing import Literal
from pydantic import BaseModel, Field
from kasflow.models import Expense


class IntentionSchema(BaseModel):
    intention: Literal["chat", "record"] = Field(
        description="Intention detected from user message"
    )


class MainState(BaseModel):
    message: str = Field(description="Input message from the user")
    intention: Literal["chat", "record"] = Field(
        description="Intention detected from user message",
        default="chat",
    )
    chat_response: str = Field(
        description="Response generated by the chat assistant", default=""
    )
    record_expenses: list[Expense] = Field(
        description="A list of expense records", default_factory=list
    )
    record_stored: bool = Field(
        description="Indicates if the expense record was successfully stored",
        default=False,
    )
    record_exception: str = Field(
        description="Exception message if there was an error storing the expense record",
        default="",
    )
